export const projectsData = [
    // { 
    //     title: "", 
    //     startDate: "Oct 1st 2022", 
    //     active: true, 
    //     deadline: "Nov 5th 2022", 
    //     teamLeads: [],
    //     link: "",
    //     body: "",
    //     tags: [],
    // },
    { 
        title: "101.xyz Course Proposal", 
        startDate: "Oct 23rd 2022", 
        active: true, 
        deadline: "Dec 1st 2022", 
        teamLeads: ["Cheesebeard"],
        link: "https://docs.google.com/document/d/1S_F6kHDoFB7nVNmoRc2wAVUhVoNRTOOmx06c-ZzGUYU/edit#",
        body: "We will design courselets for 101.xyz so anyone can earn nontransferrable badges and learn about MoonDAO",
        tags: ["Growth", "Writing"],
    },
    { 
        title: "MoonDAO Representation at the Mars Society", 
        startDate: "Oct 23re 2022", 
        active: true, 
        deadline: "Nov 1st 2022", 
        teamLeads: ["Favian", "Stellie"],
        link: "https://docs.google.com/document/d/1zYHMw01hD0mXVWXyiBrDFJu_wpapTCFjxr5aGq9dRlk/edit",
        body: "MoonDAO is becoming a recognizable name in the space community and as that reputation grows, it is important to develop connections with technical experts and thought leaders in the space community. MoonDAO has been invited to give a session talk at the Mars Society Annual Conference as a model for decentralized funding for space. This conference is a great opportunity to recruit technical experts, thought leaders, and veterans of the space industry into MoonDAO. Further it is an opportunity to showcase the strength of MoonDAO’s model.",
        tags: ["Growth"],
    },
    { 
        title: "Marshall Islands DAO Entity Creation", 
        startDate: "Oct 15th 2022", 
        active: true, 
        deadline: "Nov 15th 2022", 
        teamLeads: ["Favian"],
        link: "https://docs.google.com/document/d/1nwySQEZ92i5NLEMll3bFHPDAze6-5Pfv68THSwOgLJM/",
        body: "MoonDAO as an entity has rights and can take actions as an entity. It can own land, hire contractors and own IP. However, to exercise most of these rights, it needs to be legally recognized as a legal entity and have a bank account. This proposal would formally establish MoonDAO as a legal entity based in the Republic of Marshall Islands (RMI) as a Nonprofit DAO LLC. The RMI entity would also simplify MoonDAO’s tax obligations as outlined below. ",
        tags: ["Legal"],
    },
    { 
        title: "Stake to Vote Implementation", 
        startDate: "Oct 5th 2022", 
        active: true, 
        deadline: "Nov 5th 2022", 
        teamLeads: ["Larrotiz", "Barney"],
        link: "https://docs.google.com/document/d/19Ay6Mu43L2d09KKXr5gYmxjE6duFfD39m8cC92lqCDw/",
        body: "With Stake to Vote being part of the newly passed constitution, $MOONEY staking needs to be implemented for MoonDAO members to stake their $MOONEY to vote with $vMOONEY.",
        tags: ["Dev", "Governance"],
    },
    { 
        title: "The spacecapsule.eth Program", 
        startDate: "Oct 5th 2022", 
        active: true, 
        deadline: "Dec 31st 2022", 
        teamLeads: ["Cheesebeard"],
        link: "https://docs.google.com/document/d/1vc9Q_1NUPsck3thUw7dkJDcuAx2tMksiY-3x5b6Udcc/",
        body: "Using various forms of keypair cryptography, leverage the secure physical storage of private keys on a satellite to demonstrate the continuous accessibility of the associated public keys on their respective blockchains, with the intent to create a multiplanetary trusted setup as the backbone information network for a multiplanetary economy.",
        tags: ["Engineering", "Proof of Concept"],
    },
    { 
        title: "Email List for Onboarding & Outreach", 
        startDate: "Oct 5th 2022", 
        active: true, 
        deadline: "Dec 31st 2022", 
        teamLeads: ["ryand2d"],
        link: "https://docs.google.com/document/d/1ZEsg7H8n3_qk4AOGpynSh2NNkSrG_Yo4j41c6tDqH30/",
        body: "MoonDAO needs a central and universal means of communication with Mooney holders and those interested in participating or following the work of the organization – email is still the best way to reach the widest group of people today, straight to their inbox. Creating an automated evergreen email sequence to help onboard and educate new members, and being able to reach less active members of MoonDAO for updates and announcing votes will help to increase overall participation and involvement in MoonDAO.",
        tags: ["Writing", "Growth"],
    },
    { 
        title: "Bank Account Creationg", 
        startDate: "Sep 16th 2022", 
        active: true, 
        deadline: "Nov 25th 2022", 
        teamLeads: ["Barney"],
        link: "https://docs.google.com/document/d/1Qlc4nUDH6HaOTYoNyVkXocC-ZtksNFEs6wZ37oiJE34/",
        body: "To facilitate transactions between MoonDAO and entities that do not yet accept cryptocurrencies, a bank account is needed under MoonDAO’s name.",
        tags: ["Legal"],
    },
    { 
        title: "Guild Guidelines", 
        startDate: "Sep 16th 2022", 
        active: false, 
        deadline: "Oct 3rd 2022", 
        teamLeads: ["Luffy", "Pablo"],
        link: "https://docs.google.com/document/d/1tEpMDXDS3oZvEnyvdKV-z1VNcNVBR07XRN5QvImHCLk/",
        body: "This project aims to create the Guild Guidelines that determine how a guild is established and intended to work in a transparent and auditable way, guild's scope of work, and how compensation will work for those guilds.        ",
        tags: ["Community", "Growth"],
    },
    { 
        title: "MoonDAO a leader at the International Astronautical Federation And Space Arena", 
        startDate: "Aug 16th 2022", 
        active: false, 
        deadline: "Sep 22nd 2022", 
        teamLeads: ["Favian", "Pablo"],
        link: "https://docs.google.com/document/d/12dOaI284NGBVPeKqvNBGfnRGo_bP6LSK0Hn464BEppo/",
        body: "MoonDAO has earned the respect as a leader in the crypto community and now needs to do the same within the space travel community. This project will Focus on obtaining membership for MoonDAO in the International Astronautical Federation (IAF) and establishing a presence at relevant events. This is vital for MoonDAO because the biggest players in the industry (SpaceX, NASA, and major universities) are active participants in this federation. This is the perfect opportunity to attract and recruit engineers and space industry talent and to learn about opportunities to collaborate with some of the largest players. Also, this project seeks to sponsor NewSpace2022, which is a space travel event put on by https://newspace.spacefrontier.org/",
        tags: ["Growth"]
    },
    { 
        title: "Website Improvement", 
        startDate: "Aug 16th 2022", 
        active: true, 
        deadline: "Oct 15th 2022", 
        teamLeads: ["Larrotiz", "Barney"],
        link: "https://docs.google.com/document/d/1OG0FqTrrtQwToIP5em95uxtHzch346SCZkD3KGR3MJc/",
        body: "This project will focus on adding new interactive features to our website along with improvements to our documentation and visual appeal. This will be accomplished with various phases or “sub-projects”. The first phase is to create a MoonDAO online store to sell MoonDAO merchandising. Second, will be to implement $MOONEY staking for governance and LP rewards. The third phase will consist of updates to documentation. We will also create a dashboard to display key MoonDAO info. And lastly, we will revamp the landing/homepage with respect to the new additions. ",
        tags: ["Dev", "Writing"],
    }
  ];