export const projectsData = [
  // {
  //     title: "",
  //     startDate: "Oct 1st 2022",
  //     active: true,
  //     deadline: "Nov 5th 2022",
  //     teamLeads: [],
  //     link: "",
  //     body: "",
  //     tags: [],
  // },

  {
    title: "Increase Social Media Reach and Security",
    startDate: "Mar 6th 2023",
    active: true,
    deadline: "",
    teamLeads: ["Pablo", "ryand2d"],
    link: "https://docs.google.com/document/d/1XLijqmU-aicWkYzyIsdRsPfPyRco94kI-M6JYuqGJ3A/edit",
    body: "We are expanding our social media distribution. This proposal will lay out a foundation for getting more people to post from social channels in a secure way using LastPass, and a way of easily adding more channels as we grow using a tool to distribute messages on multiple platforms.",
    tags: ["Community", "Social Media"],
  },
  {
    title: "MoonDAO Micro Blog",
    startDate: "Mar 6th 2023",
    active: true,
    deadline: "",
    teamLeads: ["Mitchie", "ryand2d"],
    link: "https://docs.google.com/document/d/1SW2P3oi_etiIqdpTKGoPuUe1pl2iW_VAD5IzK9KtLjM/edit",
    body: "The aim of this proposal is to instantiate a native blog on the MoonDAO’s webflow-based website. The blog will implement a dynamically integrated micro-blog framework that will unlock MoonDAO’s growth and guild onboarding potential.",
    tags: ["Community"],
  },
  {
    title: "Yan KeJun Visa Support Proposal",
    startDate: "Mar 6th 2023",
    active: true,
    deadline: "",
    link: "https://docs.google.com/document/d/15VbuFS3yAkl4dXnBQ_hALnuqHmmc_Ec_0w0Dx93zY-0/",
    body: "Yan is on his third and final try for a Visa. We need funds to pay for an immigration firm to support his application. This proposal also includes a budget to pay for his flight to come for Astronaut training in Texas.",
    tags: ["Legal"],
  },
  {
    title: "MoonDAO mission to the Moon with LifeShip",
    startDate: "Feb 11th 2023",
    active: true,
    deadline: "",
    link: "https://docs.google.com/document/d/1sNqH1z_-aUdzJkPdNOY1c5jJDaF3e2WJRHgNR7YV4qY/edit",
    body: "MoonDAO wants to be part of real missions to the Moon and seeks products to engage the community and generate sustainable revenue. We propose MoonDAO joining as a partner to a DNA capsule mission to the Moon with LifeShip. The MoonDAO constitution, logo, and core documents would go in the capsule. Products would be sold and fulfilled through LifeShip for people to include their DNA and photos. LifeShip has procured the lunar mission with Firefly Aerospace for 2024 launch, designed the capsule, and will execute on the mission. This would be a statement for DAOs and governance beyond Earth, engage our community in a Moon mission, and provide a product to generate revenue.",
    tags: ["Growth", "Community"],
  },
  {
    title: "MoonDAO DAO/ETHDenver Proposal",
    startDate: "Feb 11th 2023",
    active: false,
    deadline: "",
    link: "https://docs.google.com/document/d/1bNQnO87XZwno9pBpbTr2-a0ObFdFbZTzk2p5xSDzqok/edit#heading=h.lkkrsfcy4jks",
    body: "Up to five members will be supported to attend DAODenver to increase MoonDAO’s awareness in the Ethereum community, with a $3,000 sponsorship to DAODenver.",
    tags: ["Growth"],
  },
  {
    title: "MoonDAO Weekly Newsletter, Monetization, and Incentives",
    startDate: "Jan 13th 2023",
    active: true,
    deadline: "",
    teamLeads: ["ryand2d"],
    link: "https://docs.google.com/document/d/1N95G5-dKzWaE7oQw2j-IoNVuu6xJrZoC-isFETiwRyM/edit#",
    body: "The MoonDAO Email List has proven to be a successful tool for onboarding new subscribers and keeping them informed about MoonDAO's activities. In Q1 2023, we propose continuing to make the most of the email list's capabilities by continuing the weekly Mooney Monday update email, implementing the incentives for a refer-a-friend system (currently live, but without incentives), and exploring opportunities for monetization through sponsorships and affiliate marketing. These changes will further increase participation and involvement in MoonDAO, and help to generate revenue for the organization. The MoonDAO email list currently has over 11,500 subscribers with a 44% open rate, making the email list one of our largest and most powerful means of communication. See final report from Q4.",
    tags: ["Onboarding", "Community"],
  },
  {
    title: "ZeroG Charter",
    startDate: "Jan 13th 2023",
    active: true,
    deadline: "",
    teamLeads: ["Stellie", "AriBruce"],
    link: "https://docs.google.com/document/d/11Ia6022GsiwYgCdIkQ48Hko2WbHHkTRz/edit#",
    body: "MoonDAO is organizing a charter flight and JSC tour in association with other events in the Houston, Texas area on June 9th, in partnership with Space for a Better World. The main event is a ZeroG charter flight with two astronauts in attendance. The flight has 28 seats, which will be sold to the public and of which a portion will be VIP tickets, a portion will also be reserved for raffles, various partners, and causes. In addition to the flight, MoonDAO is hosting a private tour of the Johnson Space Center. We will also be submitting a proposal for a Gala in association with Space for a Better World. The Gala is being submitted as a separate proposal to allow for targeted focus on the different portions of this event.",
    tags: ["Growth ", "Community"],
  },
  {
    title: "MoonDAO Davos Representation",
    startDate: "Dec 29th 2022",
    active: false,
    deadline: "",
    teamLeads: ["AriBruce"],
    link: "https://docs.google.com/document/d/1uHRTXefVI7h65xcNS78Iqk_YJ8ZH5rW-KKMBBY4aj4g/edit",
    body: "MoonDao is planning to send a delegation to Davos, Switzerland during the World Economic Forum. The annual meeting is one of the most prestigious programs in the world, hosting global leaders in government, business, and civil society. In addition to the main WEF meeting, there are dozens of public side conferences relevant to MoonDao such as the GBBC Blockchain Central Davos, Davos Open Forum, Blockchain Hub Davos, Hub ICEHouse, World Innovation Economics, Davos Cyber Future Dialogue, Crypto Summit, Circle Pavilion, Digital Davos, Web3 Summit, Filecoin Foundation, WISeKey Davos, TechLodge, and many more private events",
    tags: ["Growth"],
  },
  {
    title: "MoonDAO Documentary Project",
    startDate: "Dec 1st 2022",
    active: true,
    deadline: "",
    link: "https://drive.google.com/file/d/1qncBHFkEbLS1XUx1UQEaHmUIIvPAIqaR/view",
    body: "We will document our Ticket To Space winner’s journey from China to Texas, and then to space. In a long-form narrative, we have the opportunity to tell his story, the story of MoonDAO, and dive into the passions that animate web3.",
    tags: ["Community"],
  },
  {
    title: "MoonDAO Video Production Proposal",
    startDate: "Nov 12th 2022",
    active: true,
    deadline: "",
    teamLeads: ["Stellie", "Ballack"],
    link: "https://docs.google.com/document/d/1Pb3-0-TnZ5dK0NMko8s7bxns0hdnsrLp9ovX0ncqD38/edit#heading=h.3znysh7",
    body: "Using bounties, this proposal will generate up to 8 videos over the next month and begin publishing them through MoonDAOs YouTube channel and other social media accounts. This will jumpstart a MoonDAO video archive and pave the way to more sponsored content. This project will also produce multilingual content and help unify the MoonDAO community.",
    tags: ["Growth", "Community"],
  },
  {
    title: "MoonDAO Token Listing Project",
    startDate: "Nov 5th 2022",
    active: false,
    deadline: false,
    teamLeads: ["Barney", "Larrotiz"],
    link: "https://docs.google.com/document/d/1tc2mHPeyDAiGItKZtB796tpsgGHAWiq0xVamMjxinAM/edit#",
    body: "To assemble a team and budget for reaching out and negotiating token listings on centralized exchanges.",
    tags: ["Growth"],
  },
  {
    title: "MoonDAO treasury transparency",
    startDate: "Nov 5th 2022",
    active: false,
    deadline: false,
    teamLeads: ["Luffy"],
    link: "https://docs.google.com/document/d/1-FYx5b5JMh-hLtldzd6sLAuJk0Vbk1-eU3FaKK7pZC8/edit",
    body: "This project aims to make the MoonDAO Treasury transparent to the general MoonDAO community. This goal will be achieved through leveraging existing finance management platforms to track and label all inflow/outflow transactions, recipient wallets, etc.",
    tags: ["Treasury management"],
  },
  {
    title: "MoonDAO Representation at the New Worlds Conference",
    startDate: "Oct 25th 2022",
    active: false,
    deadline: false,
    teamLeads: ["Ari Eisenstat"],
    link: "https://snapshot.org/#/tomoondao.eth/proposal/0x0ad39fda7b08b797ba62fdde83a0d5680aa91fbb842ee36ad95a171ca4e45d0f",
    body: "MoonDao contributor Ari Eisenstat is invited to speak at The New Worlds Conference. This program is hosted by the Foundation for the Future and Earthlight Foundation with partner organizations such as the National Space Society, Space for Humanity, Space Frontier Foundation, The Mars Society. This conference features astronauts, NASA officials, space executives, nonprofit leaders, and academic researchers in Austin, Texas on October 28th and 29th.",
    tags: ["Growth"],
  },
  {
    title: "101.xyz Course Proposal",
    startDate: "Oct 23rd 2022",
    active: true,
    deadline: "Dec 1st 2022",
    teamLeads: ["Cheesebeard"],
    link: "https://docs.google.com/document/d/1S_F6kHDoFB7nVNmoRc2wAVUhVoNRTOOmx06c-ZzGUYU/edit#",
    body: "We will design courselets for 101.xyz so anyone can earn nontransferrable badges and learn about MoonDAO",
    tags: ["Growth", "Writing"],
  },
  {
    title: "MoonDAO Representation at the Mars Society",
    startDate: "Oct 23re 2022",
    active: true,
    deadline: "Nov 1st 2022",
    teamLeads: ["Favian", "Stellie"],
    link: "https://docs.google.com/document/d/1zYHMw01hD0mXVWXyiBrDFJu_wpapTCFjxr5aGq9dRlk/edit",
    body: "MoonDAO is becoming a recognizable name in the space community and as that reputation grows, it is important to develop connections with technical experts and thought leaders in the space community. MoonDAO has been invited to give a session talk at the Mars Society Annual Conference as a model for decentralized funding for space. This conference is a great opportunity to recruit technical experts, thought leaders, and veterans of the space industry into MoonDAO. Further it is an opportunity to showcase the strength of MoonDAO’s model.",
    tags: ["Growth"],
  },
  {
    title: "Marshall Islands DAO Entity Creation",
    startDate: "Oct 15th 2022",
    active: true,
    deadline: "Nov 15th 2022",
    teamLeads: ["Favian"],
    link: "https://docs.google.com/document/d/1nwySQEZ92i5NLEMll3bFHPDAze6-5Pfv68THSwOgLJM/",
    body: "MoonDAO as an entity has rights and can take actions as an entity. It can own land, hire contractors and own IP. However, to exercise most of these rights, it needs to be legally recognized as a legal entity and have a bank account. This proposal would formally establish MoonDAO as a legal entity based in the Republic of Marshall Islands (RMI) as a Nonprofit DAO LLC. The RMI entity would also simplify MoonDAO’s tax obligations as outlined below. ",
    tags: ["Legal"],
  },
  {
    title: "Stake to Vote Implementation",
    startDate: "Oct 5th 2022",
    active: true,
    deadline: "Nov 5th 2022",
    teamLeads: ["Larrotiz", "Barney"],
    link: "https://docs.google.com/document/d/19Ay6Mu43L2d09KKXr5gYmxjE6duFfD39m8cC92lqCDw/",
    body: "With Stake to Vote being part of the newly passed constitution, $MOONEY staking needs to be implemented for MoonDAO members to stake their $MOONEY to vote with $vMOONEY.",
    tags: ["Dev", "Governance"],
  },
  {
    title: "The spacecapsule.eth Program",
    startDate: "Oct 5th 2022",
    active: true,
    deadline: "Dec 31st 2022",
    teamLeads: ["Cheesebeard"],
    link: "https://docs.google.com/document/d/1vc9Q_1NUPsck3thUw7dkJDcuAx2tMksiY-3x5b6Udcc/",
    body: "Using various forms of keypair cryptography, leverage the secure physical storage of private keys on a satellite to demonstrate the continuous accessibility of the associated public keys on their respective blockchains, with the intent to create a multiplanetary trusted setup as the backbone information network for a multiplanetary economy.",
    tags: ["Engineering", "Proof of Concept"],
  },
  {
    title: "Email List for Onboarding & Outreach",
    startDate: "Oct 5th 2022",
    active: true,
    deadline: "Dec 31st 2022",
    teamLeads: ["ryand2d"],
    link: "https://docs.google.com/document/d/1ZEsg7H8n3_qk4AOGpynSh2NNkSrG_Yo4j41c6tDqH30/",
    body: "MoonDAO needs a central and universal means of communication with Mooney holders and those interested in participating or following the work of the organization – email is still the best way to reach the widest group of people today, straight to their inbox. Creating an automated evergreen email sequence to help onboard and educate new members, and being able to reach less active members of MoonDAO for updates and announcing votes will help to increase overall participation and involvement in MoonDAO.",
    tags: ["Writing", "Growth"],
  },
  {
    title: "Bank Account Creationg",
    startDate: "Sep 16th 2022",
    active: true,
    deadline: "Nov 25th 2022",
    teamLeads: ["Barney"],
    link: "https://docs.google.com/document/d/1Qlc4nUDH6HaOTYoNyVkXocC-ZtksNFEs6wZ37oiJE34/",
    body: "To facilitate transactions between MoonDAO and entities that do not yet accept cryptocurrencies, a bank account is needed under MoonDAO’s name.",
    tags: ["Legal"],
  },
  {
    title: "Guild Guidelines",
    startDate: "Sep 16th 2022",
    active: false,
    deadline: "Oct 3rd 2022",
    teamLeads: ["Luffy", "Pablo"],
    link: "https://docs.google.com/document/d/1tEpMDXDS3oZvEnyvdKV-z1VNcNVBR07XRN5QvImHCLk/",
    body: "This project aims to create the Guild Guidelines that determine how a guild is established and intended to work in a transparent and auditable way, guild's scope of work, and how compensation will work for those guilds.        ",
    tags: ["Community", "Growth"],
  },
  {
    title: "MoonDAO a leader at the International Astronautical Federation And Space Arena",
    startDate: "Aug 16th 2022",
    active: false,
    deadline: "Sep 22nd 2022",
    teamLeads: ["Favian", "Pablo"],
    link: "https://docs.google.com/document/d/12dOaI284NGBVPeKqvNBGfnRGo_bP6LSK0Hn464BEppo/",
    body: "MoonDAO has earned the respect as a leader in the crypto community and now needs to do the same within the space travel community. This project will Focus on obtaining membership for MoonDAO in the International Astronautical Federation (IAF) and establishing a presence at relevant events. This is vital for MoonDAO because the biggest players in the industry (SpaceX, NASA, and major universities) are active participants in this federation. This is the perfect opportunity to attract and recruit engineers and space industry talent and to learn about opportunities to collaborate with some of the largest players. Also, this project seeks to sponsor NewSpace2022, which is a space travel event put on by https://newspace.spacefrontier.org/",
    tags: ["Growth"],
  },
  {
    title: "Website Improvement",
    startDate: "Aug 16th 2022",
    active: true,
    deadline: "Oct 15th 2022",
    teamLeads: ["Larrotiz", "Barney"],
    link: "https://docs.google.com/document/d/1OG0FqTrrtQwToIP5em95uxtHzch346SCZkD3KGR3MJc/",
    body: "This project will focus on adding new interactive features to our website along with improvements to our documentation and visual appeal. This will be accomplished with various phases or “sub-projects”. The first phase is to create a MoonDAO online store to sell MoonDAO merchandising. Second, will be to implement $MOONEY staking for governance and LP rewards. The third phase will consist of updates to documentation. We will also create a dashboard to display key MoonDAO info. And lastly, we will revamp the landing/homepage with respect to the new additions. ",
    tags: ["Dev", "Writing"],
  },
];
